path: data/splits

train: train/images
val: val/images
test: test/images

nc: 150   # must match label_map size
names:
  # truncated â€“ auto-generate from label_map.json
  - window
  - man
  - tree
  - wall
  - shirt
  - building
  - person
  - ground
  - sky
  - sign
  - head
  - grass
  - light
  - pole
  - leg
  - hand
  - hair
  - trees
  - table
  - ear
  - car
  - door
  - leaves
  - woman
  - shadow
  - eye
  - fence
  - people
  - water
  - pants
  - nose
  - floor
  - handle
  - chair
  - plate
  - wheel
  - face
  - clouds
  - arm
  - leaf
  - line
  - tail
  - jacket
  - windows
  - flower
  - hat
  - spot
  - letter
  - shoe
  - sidewalk
  - tile
  - roof
  - umbrella
  - background
  - bottle
  - road
  - field
  - glass
  - cloud
  - stripe
  - street
  - logo
  - post
  - rock
  - foot
  - number
  - shorts
  - boy
  - bag
  - part
  - mouth
  - picture
  - snow
  - bush
  - dirt
  - mirror
  - tire
  - boat
  - neck
  - flowers
  - food
  - top
  - legs
  - box
  - trunk
  - lights
  - bowl
  - button
  - bench
  - counter
  - shelf
  - girl
  - helmet
  - pillow
  - train
  - brick
  - glasses
  - clock
  - reflection
  - edge
  - branch
  - cap
  - lamp
  - jeans
  - writing
  - bus
  - dog
  - house
  - lines
  - seat
  - elephant
  - paper
  - shoes
  - kite
  - horse
  - board
  - cup
  - giraffe
  - headlight
  - letters
  - plant
  - bird
  - frame
  - cabinet
  - sink
  - truck
  - bushes
  - flag
  - back
  - book
  - coat
  - rocks
  - pizza
  - tracks
  - cow
  - wing
  - ceiling
  - zebra
  - glove
  - design
  - finger
  - stripes
  - hands
  - knob
  - container
  - towel
  - hill
  - eyes
  - sand
  - vase